/**
 * Preset Consequences stories per template — funny through filthy — starring
 * celebrities, public figures, historical figures and infamous criminals. Used
 * for sample games and the in-game "random" fill buttons so players can skip
 * typing.
 *
 * Crude entries lean on consenting adults, tabloid sleaze and slapstick body
 * humour. Real violent crimes are played as farce (heists, fraud, piracy),
 * never as gore.
 */

export type PresetTone = "funny" | "cheeky" | "rude" | "crude" | "filthy";

export type PresetStory = {
  id: string;
  tone: PresetTone;
  /** Short label for UI / logs. */
  title: string;
  /** promptId → answer text (no segment wrappers). */
  answers: Record<string, string>;
};

/** Complete ready-made stories keyed by template id. */
export const PRESET_STORIES: Record<string, PresetStory[]> = {
  classic: [
    {
      id: "classic-funny",
      tone: "funny",
      title: "Gordon meets Taylor at Costco",
      answers: {
        p1: "slightly unhinged",
        p2: "Gordon Ramsay",
        p3: "aggressively glittery",
        p4: "Taylor Swift",
        p5: "a Costco sample aisle at 9am",
        p6: "argue about whether free pizza counts as a date",
        p7: "a chef's jacket made entirely of oven mitts",
        p8: "a friendship-bracelet ballgown and muddy wellies",
        p9: "screamed THIS SCALLOP IS RAW at a frozen fish display",
        p10: "wrote a 12-minute ballad about the sample lady",
        p11: "Costco hired them both as chaotic brand ambassadors",
        p12: '"Finally, a meet-cute with nutritional labelling."',
      },
    },
    {
      id: "classic-cheeky",
      tone: "cheeky",
      title: "Harry & Emily in the sauna",
      answers: {
        p1: "sweaty and optimistic",
        p2: "Harry Styles",
        p3: "dangerously charming",
        p4: "Emily Ratajkowski",
        p5: "an overcrowded hotel sauna",
        p6: "pretend they were there for the health benefits",
        p7: "nothing but a tiny towel and confidence",
        p8: "a towel that kept mysteriously slipping",
        p9: "offered her a grape like it was a marriage proposal",
        p10: "said the steam was making her philosophical about thirst",
        p11: "they were kicked out for fogging up the CCTV",
        p12: '"Well that escalated in a very moist way."',
      },
    },
    {
      id: "classic-rude",
      tone: "rude",
      title: "Pete & Kim at the afterparty",
      answers: {
        p1: "horny on main",
        p2: "Pete Davidson",
        p3: "unapologetically messy",
        p4: "Kim Kardashian",
        p5: "a bathroom queue at a Met Gala afterparty",
        p6: "escape a boring investor",
        p7: "a leather jacket and almost no shirt",
        p8: "a skintight dress that left nothing to the imagination",
        p9: "asked if she wanted to see his tattoo collection somewhere private",
        p10: "said only if he promised not to cry afterward",
        p11: "they hooked up in a coat closet and lost Kim's earring",
        p12: '"Iconic. Trashy. Content."',
      },
    },
    {
      id: "classic-crude",
      tone: "crude",
      title: "Bad Bunny & Madonna get naked",
      answers: {
        p1: "feral",
        p2: "Bad Bunny",
        p3: "legendary and unhinged",
        p4: "Madonna",
        p5: "the VIP hot tub at Coachella",
        p6: "christen the weekend properly",
        p7: "nothing but body glitter and a gold chain",
        p8: "a cone bra and an evil grin",
        p9: "got completely naked and cannonballed in",
        p10: "stripped, joined him, and rated his form a solid 8",
        p11: "security politely asked them to put on towels for the livestream",
        p12: '"Age is just a number and so is public indecency."',
      },
    },
    {
      id: "classic-crude-2",
      tone: "crude",
      title: "Florence & Timothée in Venice",
      answers: {
        p1: "art-house horny",
        p2: "Florence Pugh",
        p3: "soft-boy chaotic",
        p4: "Timothée Chalamet",
        p5: "a gondola that was definitely not built for two egos",
        p6: "rehearse an awards speech nobody asked for",
        p7: "a slip dress with nothing underneath",
        p8: "a tiny tank top and trousers hanging on for dear life",
        p9: "pulled him into a passionate snog mid-canal",
        p10: "whispered something extremely filthy in French",
        p11: "the gondolier quit on the spot and sold the story",
        p12: '"Cinema is back, baby — and so is public PDA."',
      },
    },
    {
      id: "classic-history-henry",
      tone: "crude",
      title: "Henry VIII & Cleopatra at the buffet",
      answers: {
        p1: "enormously gouty",
        p2: "Henry VIII",
        p3: "devastatingly smug",
        p4: "Cleopatra",
        p5: "an all-you-can-eat banquet with no exit strategy",
        p6: "compare body counts over a swan",
        p7: "a codpiece two sizes too ambitious",
        p8: "a gold dress held together by sheer intimidation",
        p9: "belched a marriage proposal and pulled a hamstring",
        p10: "told him she'd rather snog the asp",
        p11: "the buffet declared bankruptcy and the church split again",
        p12: '"Divorced, beheaded, bloated."',
      },
    },
    {
      id: "classic-history-napoleon",
      tone: "rude",
      title: "Napoleon & Marie Antoinette in the pantry",
      answers: {
        p1: "compensating for something",
        p2: "Napoleon Bonaparte",
        p3: "obscenely powdered",
        p4: "Marie Antoinette",
        p5: "a royal pantry stacked to the ceiling with cake",
        p6: "settle who was more insufferable",
        p7: "a hat bigger than his entire strategy",
        p8: "a wig with its own postcode and nothing else worth mentioning",
        p9: "stood on a stool to look her in the eye and slipped in the icing",
        p10: "sat on him and said it was a revolution",
        p11: "the peasants filmed it and history got a lot funnier",
        p12: '"Let them eat that."',
      },
    },
    {
      id: "classic-history-rasputin",
      tone: "filthy",
      title: "Rasputin & Catherine the Great",
      answers: {
        p1: "unwashed and unstoppable",
        p2: "Grigori Rasputin",
        p3: "imperially insatiable",
        p4: "Catherine the Great",
        p5: "a steaming palace bathhouse with the doors bolted",
        p6: "test some deeply unholy stamina rumours",
        p7: "a filthy robe, open to the navel, and absolutely nothing under it",
        p8: "a fur cape, a crown, and a smirk",
        p9: "dropped the robe entirely and announced he was a gift from God",
        p10: "inspected the gift, laughed, and requisitioned it for the empire",
        p11: "three separate courtiers fainted and one took notes",
        p12: '"No wonder they needed poison, a bullet AND a river."',
      },
    },
    {
      id: "classic-crime-capone",
      tone: "rude",
      title: "Al Capone & Bonnie Parker",
      answers: {
        p1: "sweaty and heavily armed",
        p2: "Al Capone",
        p3: "trigger-happy and gorgeous",
        p4: "Bonnie Parker",
        p5: "the back room of a speakeasy that smelled of gin and regret",
        p6: "launder money and possibly each other",
        p7: "a pinstripe suit with a bulge that was definitely a Tommy gun",
        p8: "a beret, a cigar, and a stolen fur coat over almost nothing",
        p9: "offered her a partnership and grabbed the wrong thing",
        p10: "shot his hat off and told him to try again with manners",
        p11: "the FBI raided the place and found only underwear and receipts",
        p12: '"Crime pays. Foreplay doesn\'t."',
      },
    },
    {
      id: "classic-crime-pirates",
      tone: "crude",
      title: "Blackbeard & Anne Bonny below deck",
      answers: {
        p1: "flammable and horny",
        p2: "Blackbeard",
        p3: "brutally unbothered",
        p4: "Anne Bonny",
        p5: "a rum-soaked hold with one hammock between them",
        p6: "divide the loot and possibly the hammock",
        p7: "lit fuses in his beard and trousers he'd clearly lost a bet in",
        p8: "a shirt open to the waist and two pistols where a bra should be",
        p9: "dropped his breeches and called it a treaty",
        p10: "cut the hammock down and took the whole ship instead",
        p11: "the crew mutinied out of sheer secondhand embarrassment",
        p12: '"Yo ho ho and a bottle of please stop."',
      },
    },
    {
      id: "classic-modern-elon",
      tone: "crude",
      title: "Elon Musk & Cardi B at the launch",
      answers: {
        p1: "insufferably online",
        p2: "Elon Musk",
        p3: "loud and gloriously filthy",
        p4: "Cardi B",
        p5: "a rocket launch after-party in the Texas desert",
        p6: "livestream something regrettable",
        p7: "a black T-shirt and the confidence of unearned money",
        p8: "a bodysuit so tight it needed its own engineer",
        p9: "tried a chat-up line generated by his own chatbot",
        p10: "told him where to insert the rocket, with directions",
        p11: "the launch was delayed and the clip out-performed the rocket",
        p12: '"Occupy Mars. Nobody\'s occupying you."',
      },
    },
    {
      id: "classic-history-casanova",
      tone: "filthy",
      title: "Casanova & Mata Hari",
      answers: {
        p1: "professionally shameless",
        p2: "Giacomo Casanova",
        p3: "lethally seductive",
        p4: "Mata Hari",
        p5: "a Parisian hotel suite with two exits and one bed",
        p6: "swap secrets and bodily fluids",
        p7: "a silk shirt, no trousers, and a tally book",
        p8: "seven veils and a plan to steal his trousers anyway",
        p9: "read his conquest list aloud as foreplay",
        p10: "stripped completely, added herself to page one, and pickpocketed him mid-thrust",
        p11: "she sold his diary to three governments before breakfast",
        p12: '"He was legendary. She was employed."',
      },
    },
    {
      id: "classic-history-mozart",
      tone: "crude",
      title: "Mozart & Marie Curie",
      answers: {
        p1: "giggling and gassy",
        p2: "Wolfgang Amadeus Mozart",
        p3: "mildly radioactive",
        p4: "Marie Curie",
        p5: "a Viennese salon with terrible ventilation",
        p6: "win a bet about who could clear a room faster",
        p7: "a powdered wig and breeches straining after four sausages",
        p8: "a lab coat that glowed faintly in the dark",
        p9: "farted the opening bars of a symphony and signed it",
        p10: "measured the emission and declared it a genuine discovery",
        p11: "the piece is still performed, credited to 'Anonymous, in D minor'",
        p12: '"Genius stinks."',
      },
    },
    {
      id: "classic-history-rome",
      tone: "filthy",
      title: "Nero & Caligula throw a party",
      answers: {
        p1: "criminally overindulged",
        p2: "Nero",
        p3: "certifiably deranged",
        p4: "Caligula",
        p5: "an imperial orgy that had already been going for nine days",
        p6: "outdo each other in taste-free debauchery",
        p7: "a toga worn as a loose suggestion",
        p8: "a laurel crown and literally nothing else",
        p9: "set the curtains on fire while getting his toes sucked",
        p10: "declared his own horse a senator and himself irresistible",
        p11: "the empire fell and the neighbours were relieved",
        p12: '"Rome wasn\'t built in a day, but it was ruined in one."',
      },
    },
    {
      id: "classic-crime-turpin",
      tone: "crude",
      title: "Dick Turpin & Queen Victoria",
      answers: {
        p1: "notoriously well-hung by reputation only",
        p2: "Dick Turpin",
        p3: "famously unamused",
        p4: "Queen Victoria",
        p5: "a moonlit coach road with a broken wheel",
        p6: "conduct a stand-and-deliver of unclear intent",
        p7: "a tricorn hat, a mask, and trousers with a suspicious flap",
        p8: "seven layers of mourning black and one raised eyebrow",
        p9: "demanded her jewels and dropped his trousers by mistake",
        p10: "looked, sighed, and had him arrested on aesthetic grounds",
        p11: "he was hanged and the sketch went into the national archive",
        p12: '"We are not impressed. We measured."',
      },
    },
    {
      id: "classic-modern-tabloid",
      tone: "crude",
      title: "Piers Morgan & Katie Price",
      answers: {
        p1: "unbearably self-important",
        p2: "Piers Morgan",
        p3: "surgically enhanced and proud",
        p4: "Katie Price",
        p5: "a hotel bar during an awards show nobody respected",
        p6: "trade insults for column inches",
        p7: "a suit two sizes too tight and a hairline in denial",
        p8: "a dress that had already been in three separate court cases",
        p9: "asked an invasive question and got champagne in the crotch",
        p10: "flashed the entire bar to make the front page herself",
        p11: "both got a book deal out of it within a fortnight",
        p12: '"Britain deserves this."',
      },
    },
    {
      id: "classic-crime-fraud",
      tone: "rude",
      title: "Bernie Madoff & Elizabeth Holmes",
      answers: {
        p1: "morally bankrupt",
        p2: "Bernie Madoff",
        p3: "unnervingly monotone",
        p4: "Elizabeth Holmes",
        p5: "an investor dinner where nobody had read the paperwork",
        p6: "sell each other the same lie twice",
        p7: "a suit paid for with somebody's pension",
        p8: "a black turtleneck and a voice borrowed from a stranger",
        p9: "slid his hand and a prospectus up her thigh",
        p10: "offered him a blood test and took his wallet instead",
        p11: "the fund collapsed mid-dessert and both blamed the waiter",
        p12: '"Past performance is no guarantee of pulling."',
      },
    },
    {
      id: "classic-hailee-jack",
      tone: "crude",
      title: "Hailee Steinfeld & Jack Grealish",
      answers: {
        p1: "smug and freshly moisturised",
        p2: "Hailee Steinfeld",
        p3: "shirtless and shameless",
        p4: "Jack Grealish",
        p5: "a Vegas hotel roof pool at four in the morning",
        p6: "settle who was more famous in the other's country",
        p7: "a bikini top and a bathrobe she never fastened",
        p8: "tiny shorts, calves out, and a headband holding it all together",
        p9: "peeled the robe off and dived in completely bare",
        p10: "followed her in, lost his shorts to the filter, and kept going",
        p11: "the pool was drained for cleaning and the CCTV was subpoenaed",
        p12: '"Two nations, one very wet scandal."',
      },
    },
    {
      id: "classic-sienna-rasputin",
      tone: "filthy",
      title: "Sienna Miller & Rasputin",
      answers: {
        p1: "boho and entirely unbothered",
        p2: "Sienna Miller",
        p3: "unwashed and unhinged",
        p4: "Grigori Rasputin",
        p5: "a Glastonbury yurt with incense and no lock",
        p6: "receive a spiritual healing neither of them needed",
        p7: "a crochet dress with absolutely nothing beneath it",
        p8: "a filthy monk's robe hanging fully open",
        p9: "lit a joint, dropped the dress, and asked what the fuss was about",
        p10: "demonstrated the fuss for the next four hours",
        p11: "the yurt collapsed and three neighbouring tents applauded",
        p12: '"Festival season claims another one."',
      },
    },
    {
      id: "classic-emma-boris",
      tone: "rude",
      title: "Emma Raducanu & Boris Johnson",
      answers: {
        p1: "ruthlessly competitive",
        p2: "Emma Raducanu",
        p3: "shambolic and sweating",
        p4: "Boris Johnson",
        p5: "the Wimbledon royal box during a rain delay",
        p6: "argue about who had ruined Britain's summer more",
        p7: "tennis whites so short the umpire needed a moment",
        p8: "a suit that had clearly been slept in and a shirt gaping open",
        p9: "served a ball directly into his crotch at 120mph",
        p10: "went down honking like a wounded goose with his flies undone",
        p11: "the BBC cut to the pigeons and the clip broke the internet",
        p12: '"Game, set, and a full public inquiry."',
      },
    },
  ],

  short: [
    {
      id: "short-funny",
      tone: "funny",
      title: "Ryan & Zendaya at Pret",
      answers: {
        p1: "Ryan Reynolds",
        p2: "Zendaya",
        p3: "a Pret queue that had emotionally broken everyone",
        p4: '"Is the avocado toast judging me or is that just my face?"',
        p5: '"Both. Sit with it."',
        p6: "they accidentally stole each other's oat-milk lattes and bonded over the crime",
        p7: "they launched a podcast called Soft Boys Hate Hard Foam",
      },
    },
    {
      id: "short-cheeky",
      tone: "cheeky",
      title: "Idris & Margot in first class",
      answers: {
        p1: "Idris Elba",
        p2: "Margot Robbie",
        p3: "the first-class bar on a red-eye to LA",
        p4: '"I don\'t usually do this, but your champagne looks lonely."',
        p5: '"It\'s about to get a roommate."',
        p6: "they shared a blanket and a frankly inappropriate amount of eye contact",
        p7: "the flight attendant asked them to keep the turbulence to themselves",
      },
    },
    {
      id: "short-rude",
      tone: "rude",
      title: "Travis & Sydney backstage",
      answers: {
        p1: "Travis Kelce",
        p2: "Sydney Sweeney",
        p3: "a suspiciously empty backstage corridor",
        p4: '"Nice dress. Shame if someone had to help you out of it."',
        p5: '"Bold of you to assume you\'d be invited."',
        p6: "they made out against a flight case until a roadie coughed loudly",
        p7: "TMZ ran the headline and their agents both sighed in unison",
      },
    },
    {
      id: "short-crude",
      tone: "crude",
      title: "Post Malone & Dua get filthy",
      answers: {
        p1: "Post Malone",
        p2: "Dua Lipa",
        p3: "a sticky VIP bathroom at a festival",
        p4: '"Wanna do something we\'ll both deny tomorrow?"',
        p5: '"Lock the door and don\'t be gentle."',
        p6: "they had a very loud, very vertical encounter against the sink",
        p7: "someone filmed the locked-door soundtrack and it went platinum in group chats",
      },
    },
    {
      id: "short-crude-2",
      tone: "crude",
      title: "Pedro & Aubrey gone wild",
      answers: {
        p1: "Pedro Pascal",
        p2: "Aubrey Plaza",
        p3: "an Airbnb with one bed and zero shame",
        p4: '"I brought wine and bad intentions."',
        p5: '"Good. I\'m already halfway undressed."',
        p6: "they got naked, ordered pizza mid-romp, and tipped the driver without opening the door",
        p7: "the neighbours filed a noise complaint titled 'enthusiastic Spanish'",
      },
    },
    {
      id: "short-history-cleo",
      tone: "filthy",
      title: "Cleopatra & Julius Caesar",
      answers: {
        p1: "Cleopatra",
        p2: "Julius Caesar",
        p3: "a milk bath big enough for a small navy",
        p4: '"Drop the toga, general. That\'s an order from a god."',
        p5: '"I came, I saw, I\'m already undressed."',
        p6: "they conquered each other twice before the milk went warm",
        p7: "Rome got a civil war and the bath got condemned",
      },
    },
    {
      id: "short-history-henry",
      tone: "crude",
      title: "Henry VIII & Anne Boleyn",
      answers: {
        p1: "Henry VIII",
        p2: "Anne Boleyn",
        p3: "a drafty castle corridor that stank of wet dog",
        p4: '"I\'ve broken with Rome, so get your kit off."',
        p5: '"Ring first, gout monster."',
        p6: "he wrestled her out of a corset and pulled something in his groin",
        p7: "a whole religion was founded so he could keep trying",
      },
    },
    {
      id: "short-history-napoleon",
      tone: "filthy",
      title: "Napoleon & Joséphine",
      answers: {
        p1: "Napoleon Bonaparte",
        p2: "Joséphine de Beauharnais",
        p3: "a campaign tent smelling of horses and ambition",
        p4: '"Don\'t wash. I\'ll be home in three days."',
        p5: '"Then hurry, little general, I\'ve gone feral."',
        p6: "he abandoned an actual battle to get his trousers off",
        p7: "France lost a province and gained the filthiest letters in history",
      },
    },
    {
      id: "short-crime-bonnie",
      tone: "rude",
      title: "Bonnie & Clyde on the run",
      answers: {
        p1: "Bonnie Parker",
        p2: "Clyde Barrow",
        p3: "a stolen car with the back seat already ruined",
        p4: '"Rob the bank first, then me."',
        p5: '"Can we do it in the other order?"',
        p6: "they did it in the other order and were late for the robbery",
        p7: "the getaway driver quit and wrote a very detailed statement",
      },
    },
    {
      id: "short-crime-capone",
      tone: "rude",
      title: "Al Capone & Eliot Ness",
      answers: {
        p1: "Al Capone",
        p2: "Eliot Ness",
        p3: "a raided brothel with everyone still half-dressed",
        p4: '"You can arrest me, but put your trousers back on first."',
        p5: '"That\'s evidence now, Alphonse."',
        p6: "they got handcuffed together and had to share a very small taxi",
        p7: "the tax office got him anyway and the taxi driver got a memoir",
      },
    },
    {
      id: "short-history-rasputin",
      tone: "filthy",
      title: "Rasputin & the palace maid",
      answers: {
        p1: "Grigori Rasputin",
        p2: "Anna Vyrubova",
        p3: "a candlelit chapel with a lockable door",
        p4: '"Sin is only sin if you\'re quiet about it."',
        p5: '"Then God is about to hear everything."',
        p6: "the entire congregation heard the healing session and took notes",
        p7: "the Romanovs blamed the plumbing and history blamed them",
      },
    },
    {
      id: "short-modern-kanye",
      tone: "crude",
      title: "Kanye & Julia in the hotel lobby",
      answers: {
        p1: "Kanye West",
        p2: "Julia Fox",
        p3: "a hotel lobby with a photographer already booked",
        p4: '"I made your outfit. Now take it off."',
        p5: '"Only if the paparazzi get the angle right."',
        p6: "they dry-humped in front of a lift and called it a fashion campaign",
        p7: "the lift attendant sold the footage and retired to Portugal",
      },
    },
    {
      id: "short-crime-pirates",
      tone: "crude",
      title: "Calico Jack & Mary Read",
      answers: {
        p1: "Calico Jack",
        p2: "Mary Read",
        p3: "a stolen sloop with a mouldy hammock",
        p4: '"Fancy plundering something a bit closer to hand?"',
        p5: '"Only if you shut up and let me steer."',
        p6: "they rocked the hammock so hard it took the mast with it",
        p7: "the crew rowed home and Jack was hanged fully clothed for once",
      },
    },
    {
      id: "short-modern-love-island",
      tone: "filthy",
      title: "Love Island's finest",
      answers: {
        p1: "Molly-Mae Hague",
        p2: "Tommy Fury",
        p3: "the hideaway with 24 cameras and zero shame",
        p4: '"The mic pack stays on. Everything else goes."',
        p5: '"Producers are going to need a bigger bleep button."',
        p6: "they went at it under a duvet while the nation watched the sheets move",
        p7: "Ofcom got 4,000 complaints and ITV got a record audience",
      },
    },
    {
      id: "short-crime-escobar",
      tone: "crude",
      title: "Pablo Escobar & his hippo",
      answers: {
        p1: "Pablo Escobar",
        p2: "Griselda Blanco",
        p3: "a jungle mansion with a swimming pool full of hippos",
        p4: '"I own a country and a zoo. What do you own?"',
        p5: '"Your suppliers. Now get in the pool."',
        p6: "they had a filthy poolside afternoon while a hippo watched judgementally",
        p7: "the hippos escaped, bred, and are still ruining Colombia's rivers",
      },
    },
    {
      id: "short-history-shakespeare",
      tone: "crude",
      title: "Shakespeare & Elizabeth I",
      answers: {
        p1: "William Shakespeare",
        p2: "Queen Elizabeth I",
        p3: "a plague-closed theatre with one dry seat",
        p4: '"Shall I compare thee to a summer\'s arse?"',
        p5: '"Compare it closer, playwright."',
        p6: "they rewrote a sonnet on the floor with no clothes and one quill",
        p7: "the folio was censored and the missing pages sold for a fortune",
      },
    },
    {
      id: "short-hailee",
      tone: "filthy",
      title: "Hailee Steinfeld & Pedro Pascal",
      answers: {
        p1: "Hailee Steinfeld",
        p2: "Pedro Pascal",
        p3: "a press-tour hotel room with the junket running two hours late",
        p4: '"Interviews are over. Get on the bed, papi."',
        p5: '"I\'m contractually obliged to say yes to everything today."',
        p6: "they wrecked the room so thoroughly the publicist paid cash for the sheets",
        p7: "the junket footage was scrapped and the housekeeping tip was enormous",
      },
    },
    {
      id: "short-sienna",
      tone: "crude",
      title: "Sienna Miller & Jude Law",
      answers: {
        p1: "Sienna Miller",
        p2: "Jude Law",
        p3: "a Notting Hill pub garden crawling with paparazzi",
        p4: '"Cheat on me again and I\'ll sell your nudes myself."',
        p5: '"Take the photos first, they were good angles."',
        p6: "got off with each other against the beer garden fence out of pure spite",
        p7: "the tabloids paid six figures and both denied it on daytime telly",
      },
    },
    {
      id: "short-emma",
      tone: "crude",
      title: "Emma Raducanu & Carlos Alcaraz",
      answers: {
        p1: "Emma Raducanu",
        p2: "Carlos Alcaraz",
        p3: "the mixed-doubles locker room after a five-set thriller",
        p4: '"Nice topspin. Shame about the grunting."',
        p5: '"You grunted louder. Want to prove it in here?"',
        p6: "they went at it on the physio bench until it snapped clean in half",
        p7: "the ATP invoiced them jointly and the physio requested a transfer",
      },
    },
  ],

  adventure: [
    {
      id: "adventure-funny",
      tone: "funny",
      title: "Keanu vs the Wi-Fi dragon",
      answers: {
        p1: "Keanu Reeves",
        p2: "a quiet suburb where the Wi-Fi was sentient and petty",
        p3: "the router whispered his true name and challenged him to a duel",
        p4: "a dragon made of buffering circles and unpaid invoices",
        p5: "politely said 'whoa' and unplugged it with honour",
        p6: "even legends need a password reset sometimes",
        p7: "he opened a dojo for emotionally supportive IT support",
      },
    },
    {
      id: "adventure-cheeky",
      tone: "cheeky",
      title: "Rihanna's treasure hunt",
      answers: {
        p1: "Rihanna",
        p2: "a yacht so expensive it had its own therapist",
        p3: "a treasure map tattooed on a very attractive stranger",
        p4: "pirates who demanded she sing for safe passage — and then tip",
        p5: "sang one verse, winked, and stole their ship anyway",
        p6: "power looks better with a little theft",
        p7: "she launched a perfume called Plunder Me",
      },
    },
    {
      id: "adventure-rude",
      tone: "rude",
      title: "The Rock's cursed underwear",
      answers: {
        p1: "Dwayne Johnson",
        p2: "a gym that only opened at 3am for the spiritually jacked",
        p3: "a cursed pair of underwear promised eternal gains",
        p4: "a jealousy demon living in the squat rack",
        p5: "bench-pressed the demon while flexing emotionally",
        p6: "gains mean nothing if you can't clap your cheeks in victory",
        p7: "he filmed a masterclass called 'Smashing Evil (and Personal Bests)'",
      },
    },
    {
      id: "adventure-crude",
      tone: "crude",
      title: "Billie vs the horny oracle",
      answers: {
        p1: "Billie Eilish",
        p2: "a misty valley where everyone's secrets were sticky",
        p3: "an oracle demanded a kiss… and then slightly more",
        p4: "a monster that fed exclusively on repressed thirst",
        p5: "got naked under the moonlight and starved it with radical honesty",
        p6: "shame is just horniness wearing a hoodie",
        p7: "the valley became a clothing-optional wellness retreat",
      },
    },
    {
      id: "adventure-crude-2",
      tone: "crude",
      title: "Michael B. Jordan's wet quest",
      answers: {
        p1: "Michael B. Jordan",
        p2: "a coastal village obsessed with shirtless prophecy",
        p3: "the sea goddess demanded he prove his 'heroic stamina'",
        p4: "a kraken with wandering tentacles and worse manners",
        p5: "wrestled it into submission in the surf, mostly undressed",
        p6: "destiny looks better wet",
        p7: "the village erected a statue that needed a parental advisory plaque",
      },
    },
    {
      id: "adventure-history-genghis",
      tone: "crude",
      title: "Genghis Khan's family tree",
      answers: {
        p1: "Genghis Khan",
        p2: "a steppe where every single tent was somehow related to him",
        p3: "a prophecy declared he had run out of unrelated women",
        p4: "an entire continent of increasingly awkward introductions",
        p5: "rode west with his trousers already half off",
        p6: "conquest is just aggressive networking",
        p7: "0.5% of the planet now has his jawline and his stamina",
      },
    },
    {
      id: "adventure-history-cleopatra",
      tone: "filthy",
      title: "Cleopatra and the asp",
      answers: {
        p1: "Cleopatra",
        p2: "a palace where the milk baths never went cold",
        p3: "a Roman general arrived asking for directions and a favour",
        p4: "two rival empires who both wanted her naked and compliant",
        p5: "seduced both of them, separately, in the same afternoon",
        p6: "an empire runs on leverage and lubricant",
        p7: "she went out on her own terms with a snake and a smirk",
      },
    },
    {
      id: "adventure-crime-blackbeard",
      tone: "crude",
      title: "Blackbeard's very wet quest",
      answers: {
        p1: "Blackbeard",
        p2: "a rum-drenched port where the whole harbour owed him money",
        p3: "a mermaid offered him treasure for something extremely specific",
        p4: "a naval blockade and a rash he refused to discuss",
        p5: "boarded the flagship trouserless, screaming, and on fire",
        p6: "fear is just confidence with the flies undone",
        p7: "his head ended up on a spike and his legend in every brothel",
      },
    },
    {
      id: "adventure-history-rasputin",
      tone: "filthy",
      title: "Rasputin's unkillable night",
      answers: {
        p1: "Grigori Rasputin",
        p2: "a Siberian village where the beer was warm and the morals warmer",
        p3: "a vision told him to heal the aristocracy from the waist down",
        p4: "assassins with cake, poison, bullets and a very cold river",
        p5: "survived all four while still mostly undressed",
        p6: "you cannot murder a man who has nothing left to lose but his trousers",
        p7: "his preserved trophy allegedly sits in a museum in St Petersburg",
      },
    },
    {
      id: "adventure-history-boudica",
      tone: "rude",
      title: "Boudica burns it all down",
      answers: {
        p1: "Boudica",
        p2: "a muddy Iron Age village that the Romans kept taxing",
        p3: "a Roman governor grabbed the wrong queen's backside",
        p4: "an entire legion who thought a woman couldn't hold a grudge",
        p5: "burned three cities down and used his standard as a toilet",
        p6: "never underestimate a furious woman with a chariot",
        p7: "London had to be rebuilt and the Romans stopped touching people",
      },
    },
    {
      id: "adventure-crime-capone",
      tone: "crude",
      title: "Capone and the Prohibition bathtub",
      answers: {
        p1: "Al Capone",
        p2: "a Chicago tenement where every bathtub brewed gin",
        p3: "the mayor demanded booze, protection, and one very odd favour",
        p4: "a rival gang, the taxman, and a truly ruinous case of syphilis",
        p5: "held a summit in a brothel wearing nothing but a towel and a grin",
        p6: "you can buy anything except a clean blood test",
        p7: "the taxman got him and the bathtub got a blue plaque",
      },
    },
    {
      id: "adventure-history-napoleon",
      tone: "crude",
      title: "Napoleon's little campaign",
      answers: {
        p1: "Napoleon Bonaparte",
        p2: "a Corsican village where everyone was taller than him",
        p3: "an oracle promised him Europe if he stopped compensating",
        p4: "Russian winter, English cannons, and relentless size jokes",
        p5: "invaded anyway with his hand suspiciously inside his coat",
        p6: "ambition is what happens when the trousers don't fit",
        p7: "he died on a tiny island and the jokes never stopped",
      },
    },
    {
      id: "adventure-history-houdini",
      tone: "rude",
      title: "Houdini's stuck escape",
      answers: {
        p1: "Harry Houdini",
        p2: "a vaudeville theatre that smelled of sweat and sawdust",
        p3: "a rival dared him to escape a tank completely naked",
        p4: "a locked trunk, wet knots, and a very unhelpful erection",
        p5: "dislocated both shoulders and burst out to a standing ovation",
        p6: "there is no lock that beats sheer bloody-minded nudity",
        p7: "the trunk toured for decades with a modesty curtain attached",
      },
    },
    {
      id: "adventure-history-casanova",
      tone: "filthy",
      title: "Casanova's last conquest",
      answers: {
        p1: "Giacomo Casanova",
        p2: "a Venetian palazzo where every window led to a different bedroom",
        p3: "a wager claimed there was one woman in Venice he couldn't have",
        p4: "her three brothers, two husbands, and a dodgy hip",
        p5: "climbed in the window naked, mid-storm, and delivered",
        p6: "reputation is the only thing that gets harder with age",
        p7: "he died a librarian, surrounded by notes nobody dared publish",
      },
    },
    {
      id: "adventure-crime-cooper",
      tone: "rude",
      title: "D.B. Cooper's exit",
      answers: {
        p1: "D.B. Cooper",
        p2: "a beige airport lounge in 1971 where nobody checked anything",
        p3: "a briefcase, a bomb hoax, and a truly filthy idea",
        p4: "two hundred grand, one parachute, and no trousers with pockets",
        p5: "jumped out of the back of the plane mid-cocktail",
        p6: "the best crime is the one nobody can photograph",
        p7: "he vanished forever and the FBI file is still open and furious",
      },
    },
    {
      id: "adventure-modern-musk",
      tone: "crude",
      title: "Musk's Mars honeymoon",
      answers: {
        p1: "Elon Musk",
        p2: "a Texas launchpad surrounded by unpaid contractors",
        p3: "a poll on his own website told him to colonise something",
        p4: "cosmic radiation, no plumbing, and a zero-gravity erection",
        p5: "livestreamed the whole ordeal and monetised the footage",
        p6: "space is just a bigger room to be weird in",
        p7: "Mars got a flag, a lawsuit, and a very stained spacesuit",
      },
    },
    {
      id: "adventure-hailee",
      tone: "crude",
      title: "Hailee Steinfeld's dodgy audition",
      answers: {
        p1: "Hailee Steinfeld",
        p2: "a Los Angeles rehearsal studio with terrible air conditioning",
        p3: "a producer promised her the role for one very specific favour",
        p4: "a casting couch, a bad NDA, and a director with wandering hands",
        p5: "kneed him in the groin and stole the whole script on the way out",
        p6: "you should never audition for anyone who locks the door",
        p7: "she directed it herself and he ended up on a very long list",
      },
    },
    {
      id: "adventure-sienna",
      tone: "filthy",
      title: "Sienna Miller's festival vision quest",
      answers: {
        p1: "Sienna Miller",
        p2: "a muddy field where everyone had lost their tent and their morals",
        p3: "a shaman insisted her aura needed clearing from the inside",
        p4: "three grams of something unlicensed and a very persistent drummer",
        p5: "stripped completely, danced through the mud, and out-partied the whole crew",
        p6: "clothes are just a coping mechanism for the sober",
        p7: "the photos ran for a fortnight and became a fashion campaign",
      },
    },
    {
      id: "adventure-emma",
      tone: "rude",
      title: "Emma Raducanu vs Centre Court",
      answers: {
        p1: "Emma Raducanu",
        p2: "a Bromley tennis club where the vending machine ate everyone's money",
        p3: "a wild card arrived demanding she win a Grand Slam by Sunday",
        p4: "a wardrobe malfunction, a heckler, and one very sweaty umpire",
        p5: "played the last set with her kit half undone and won anyway",
        p6: "the crowd is only rooting for you until the skirt rides up",
        p7: "she took the trophy and the heckler was escorted out in cuffs",
      },
    },
  ],

  neutral: [
    {
      id: "neutral-funny",
      tone: "funny",
      title: "Tom & Selena at silent disco",
      answers: {
        p1: "Tom Holland",
        p2: "Selena Gomez",
        p3: "a silent disco where nobody was on the same song",
        p4: '"Are you dancing to ABBA or having a medical event?"',
        p5: '"Both. Commit."',
        p6: "started a headphone swap cult called Beat Blind Dating",
        p7: "they became millionaires selling earplugs as 'relationship tools'",
      },
    },
    {
      id: "neutral-cheeky",
      tone: "cheeky",
      title: "Chris & Gal at the museum",
      answers: {
        p1: "Chris Hemsworth",
        p2: "Gal Gadot",
        p3: "a museum after-hours party with too much champagne",
        p4: '"I could lift that statue. Or you. Your call."',
        p5: '"Put the statue down and buy me another drink."',
        p6: "sneaked into the coat check for a very classical makeout",
        p7: "security banned gods from the antiquities wing",
      },
    },
    {
      id: "neutral-rude",
      tone: "rude",
      title: "Doja & The Weeknd texting",
      answers: {
        p1: "Doja Cat",
        p2: "The Weeknd",
        p3: "a rooftop bar where the Wi-Fi password was 'thirsty'",
        p4: '"Your playlist is mid but your face is doing overtime."',
        p5: '"Come closer and say that again."',
        p6: "left early to continue the argument horizontally",
        p7: "their group chat named the night 'professional misconduct'",
      },
    },
    {
      id: "neutral-crude",
      tone: "crude",
      title: "Megan & Machine Gun Kelly uncensored",
      answers: {
        p1: "Megan Thee Stallion",
        p2: "Machine Gun Kelly",
        p3: "a karaoke booth that should have had soundproofing",
        p4: '"Sing less. Touch more."',
        p5: '"Say please and take your jeans off."',
        p6: "got naked between songs and somehow still finished Bohemian Rhapsody",
        p7: "the booth was retired and sold as an NFT called 'Echoes of Bad Decisions'",
      },
    },
    {
      id: "neutral-crude-2",
      tone: "crude",
      title: "Sabrina & Shawn after hours",
      answers: {
        p1: "Sabrina Carpenter",
        p2: "Shawn Mendes",
        p3: "a recording studio at 2am with one working couch",
        p4: '"This track needs more tension. Or less clothing."',
        p5: '"I vote less clothing. Immediately."',
        p6: "scrapped the song, got undressed, and made a much better memory",
        p7: "the engineer pretended not to hear and asked for hazard pay",
      },
    },
    {
      id: "neutral-history-freud",
      tone: "crude",
      title: "Freud & Jung on the couch",
      answers: {
        p1: "Sigmund Freud",
        p2: "Carl Jung",
        p3: "a Vienna consulting room with one very sturdy couch",
        p4: '"Tell me about your mother, and then take your shirt off."',
        p5: '"Everything you say is about your own genitals, Sigmund."',
        p6: "wrestled on the couch until it collapsed and both blamed the subconscious",
        p7: "psychoanalysis split in two and the couch went into a museum",
      },
    },
    {
      id: "neutral-history-tesla",
      tone: "rude",
      title: "Tesla & Marie Curie",
      answers: {
        p1: "Nikola Tesla",
        p2: "Marie Curie",
        p3: "a laboratory that sparked every time anyone got excited",
        p4: '"I have never touched a woman, but I have excellent voltage."',
        p5: '"Then hold this and don\'t scream."',
        p6: "electrocuted themselves into a very memorable evening",
        p7: "the lab burned down and both won prizes for unrelated work",
      },
    },
    {
      id: "neutral-history-churchill",
      tone: "crude",
      title: "Churchill & Stalin at the summit",
      answers: {
        p1: "Winston Churchill",
        p2: "Joseph Stalin",
        p3: "a Yalta bathroom at four in the morning",
        p4: '"I am drunk, but tomorrow I shall be drunk and right."',
        p5: '"You are drunk and standing in my urinal, comrade."',
        p6: "carved up half of Europe while one of them was still mid-stream",
        p7: "the map was signed with a wet cuff and it ruined a century",
      },
    },
    {
      id: "neutral-crime-krays",
      tone: "rude",
      title: "The Krays hold court",
      answers: {
        p1: "Ronnie Kray",
        p2: "Barbara Windsor",
        p3: "an East End pub where nobody had ever seen anything, ever",
        p4: '"Nice frock. Be a shame if the tailor had an accident."',
        p5: '"Buy me a gin and keep your hands where I can count them."',
        p6: "snogged in the snug while three witnesses developed amnesia",
        p7: "the pub burned down for insurance reasons and nobody was charged",
      },
    },
    {
      id: "neutral-crime-abagnale",
      tone: "crude",
      title: "Frank Abagnale & Ma Barker",
      answers: {
        p1: "Frank Abagnale",
        p2: "Ma Barker",
        p3: "a hotel check-in desk with three fake passports on it",
        p4: '"I\'m a pilot, a doctor, and available."',
        p5: '"You\'re a child, and you\'re paying for this room."',
        p6: "conned the honeymoon suite and trashed it out of spite",
        p7: "the FBI arrested them both and the hotel kept the deposit",
      },
    },
    {
      id: "neutral-history-victoria",
      tone: "crude",
      title: "Queen Victoria & John Brown",
      answers: {
        p1: "Queen Victoria",
        p2: "John Brown",
        p3: "a draughty Highland lodge with one working fireplace",
        p4: '"Warm the bed, Brown. Thoroughly."',
        p5: '"Aye ma\'am, and mind the sporran."',
        p6: "spent forty years pretending it was purely about the horses",
        p7: "her son burned every diary and the rumours got filthier anyway",
      },
    },
    {
      id: "neutral-modern-bezos",
      tone: "crude",
      title: "Bezos & Nicki Minaj on the yacht",
      answers: {
        p1: "Jeff Bezos",
        p2: "Nicki Minaj",
        p3: "a superyacht so big it needed a support yacht",
        p4: '"Everything on this boat is same-day delivery."',
        p5: '"Then deliver something impressive for once."',
        p6: "got very loud in a hot tub while the crew found urgent tasks elsewhere",
        p7: "the crew unionised and the footage was buried under an NDA",
      },
    },
    {
      id: "neutral-history-vangogh",
      tone: "rude",
      title: "Van Gogh & Frida Kahlo",
      answers: {
        p1: "Vincent van Gogh",
        p2: "Frida Kahlo",
        p3: "a paint-splattered studio with no heating and no rules",
        p4: '"I only have one ear, so shout the filthy bits."',
        p5: '"Then get on the floor, I paint better from above."',
        p6: "rolled naked through the wet canvases and called it a collaboration",
        p7: "the ruined painting sold for more than either of them ever earned alive",
      },
    },
    {
      id: "neutral-modern-simon",
      tone: "crude",
      title: "Simon Cowell & Gemma Collins",
      answers: {
        p1: "Simon Cowell",
        p2: "Gemma Collins",
        p3: "a green room with a broken sofa and a full bar",
        p4: '"That was the worst audition of my life. Do it again, topless."',
        p5: '"I\'m the GC, darling, you couldn\'t handle the encore."',
        p6: "broke the sofa in a way that legal had to be told about",
        p7: "the show was renewed for six series and the sofa was incinerated",
      },
    },
    {
      id: "neutral-crime-luciano",
      tone: "rude",
      title: "Lucky Luciano & Belle Starr",
      answers: {
        p1: "Lucky Luciano",
        p2: "Belle Starr",
        p3: "a card table with more pistols than chips on it",
        p4: '"Lose the corset, we\'re playing for skin now."',
        p5: '"Deal one more crooked card and you\'ll lose more than that."',
        p6: "shot the chandelier out and finished the hand half-dressed",
        p7: "the saloon was condemned and both denied ever being there",
      },
    },
    {
      id: "neutral-hailee",
      tone: "crude",
      title: "Hailee Steinfeld & Timothée Chalamet",
      answers: {
        p1: "Hailee Steinfeld",
        p2: "Timothée Chalamet",
        p3: "an awards-season photo call with a very flimsy backdrop",
        p4: '"Smile for the cameras and keep your hand where it is."',
        p5: '"That is not my hand."',
        p6: "collapsed through the backdrop mid-grope in front of forty photographers",
        p7: "the picture won a press award and both publicists aged a decade",
      },
    },
    {
      id: "neutral-sienna",
      tone: "filthy",
      title: "Sienna Miller & Idris Elba",
      answers: {
        p1: "Sienna Miller",
        p2: "Idris Elba",
        p3: "a members' club bathroom in Soho with a queue outside",
        p4: '"Ten minutes. Don\'t waste any of them."',
        p5: '"I only need eight, but I\'ll show off."',
        p6: "went at it against the sink while the queue timed them out of respect",
        p7: "the club revoked both memberships and doubled its waiting list",
      },
    },
    {
      id: "neutral-emma",
      tone: "rude",
      title: "Emma Raducanu & Jack Grealish",
      answers: {
        p1: "Emma Raducanu",
        p2: "Jack Grealish",
        p3: "a sponsor's box where the free champagne never stopped",
        p4: '"You run less in ninety minutes than I do in one rally."',
        p5: '"Come downstairs and I\'ll show you my stamina."',
        p6: "snogged in the stairwell until a steward coughed himself hoarse",
        p7: "both sponsors issued statements and neither denied a thing",
      },
    },
  ],
};

function pickIndex(length: number): number {
  return Math.floor(Math.random() * length);
}

/** All preset stories for a template (falls back to classic). */
export function getPresetsForTemplate(templateId: string): PresetStory[] {
  return PRESET_STORIES[templateId] ?? PRESET_STORIES.classic;
}

/** Pick one full preset story at random for a template. */
export function pickRandomPresetStory(templateId: string): PresetStory {
  const presets = getPresetsForTemplate(templateId);
  return presets[pickIndex(presets.length)];
}

/**
 * Pick a random answer for a single prompt from across that template's
 * presets (so fields stay thematically consistent with the library).
 */
export function pickRandomPresetAnswer(
  templateId: string,
  promptId: string
): string | null {
  const options = getPresetsForTemplate(templateId)
    .map((s) => s.answers[promptId]?.trim())
    .filter((a): a is string => Boolean(a));
  if (options.length === 0) return null;
  return options[pickIndex(options.length)];
}

/** Fill every prompt from one randomly chosen preset story. */
export function pickRandomPresetAnswers(
  templateId: string
): Record<string, string> {
  return { ...pickRandomPresetStory(templateId).answers };
}
